### ISSUE TITLE
addon causes Ember to attempt to watch demo page app tests directory

### ISSUE THREAD

**Issue by talexand** [plusacht/ember-bootstrap-datetimepicker#29]
Including the following lines in `Brocfile.js` in my existing Ember project causes this issue:

```js
var EmberAddon = require('ember-cli/lib/broccoli/ember-addon');

var app = new EmberAddon({
  'ember-bootstrap-datetimepicker': { 
    'importBootstrapCSS': true,
    'importBootstrapJS': true,
    'importFontAwesome': true
  }
});
```

Error on `ember server`:

````
Attempting to watch missing directory: tests/dummy/app
Error: Attempting to watch missing directory: tests/dummy/app
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/home/user/unisync/projects/scrubbed/project/ember/node_modules/ember-cli/node_modules/broccoli-sane-watcher/index.js:90:11)
    at /home/user/unisync/projects/scrubbed/project/ember/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:67:35
    at lib$rsvp$$internal$$tryCatch (/home/user/unisync/projects/scrubbed/project/ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/home/user/unisync/projects/scrubbed/project/ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at /home/user/unisync/projects/scrubbed/project/ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1095:13
    at lib$rsvp$asap$$flush (/home/user/unisync/projects/scrubbed/project/ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
```

Environment:

- ember-cli 0.2.3
- node 0.12.0
- npm 2.7.6

**Comment by talexand** [comment]
Further investigation: this seems to come from the `EmberAddon()` function, which constructs an app with the following:

```js
this.appConstructor(merge(options, {
    name: 'dummy',
    configPath: './tests/dummy/config/environment',
    trees: {
      app: 'tests/dummy/app',
      styles: 'tests/dummy/app/styles',
      templates: 'tests/dummy/app/templates',
      public: 'tests/dummy/public',
      tests: new Funnel('tests', {
        exclude: [ /^dummy/ ]
      })
    },
```

**Comment by talexand** [comment]
The above were fixed by `bower install bootstrap`, although this left out the Font Awesome dependencies, which I opted to skip (`'importFontAwesome': false`).
