### ISSUE TITLE
Cannot find module 'eonasdan-bootstrap-datetimepicker'

### ISSUE THREAD

**Issue by eddiesholl** [plusacht/ember-bootstrap-datetimepicker#77]
We recently took an npm dependency on v1.0.4. When running 'ember build -w', I am seeing the following error:

Cannot find module 'eonasdan-bootstrap-datetimepicker'
Error: Cannot find module 'eonasdan-bootstrap-datetimepicker'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.require.resolve (internal/module.js:23:19)
    at Class.module.exports.treeForVendor (/home/eddie/dev/cooltrax/refresh/node_modules/ember-bootstrap-datetimepicker/index.js:59:38)

I think this means it needs to be promoted in the package.json from devDependencies to dependencies, right?

**Comment by jasonmit** [comment]
ember g ember-bootstrap-datetimepicker
